"""Motor principal de BlockCAD Remake."""

from .commands import (
    AddPartCommand,
    Command,
    MacroCommand,
    MovePartCommand,
    RecolorPartCommand,
    RemovePartCommand,
    RotateClockwiseCommand,
    RotateCommand,
    SetOrientationCommand,
    TranslatePartCommand,
)
from .editor import BlockEditor
from .dsl import parse_model, parse_model_con_lineas
from .errors import (
    BlockCADError,
    CollisionError,
    CommandError,
    DslError,
    DuplicateInstanceError,
    DuplicatePartError,
    InstanceNotFoundError,
    InvalidColorError,
    InvalidFormatError,
    InvalidGeometryError,
    InvalidPartError,
    InvalidPlacementError,
    PartNotFoundError,
    TransactionError,
)
from .geometry import (
    LADRILLO,
    LDU_MM,
    MEDIO_MODULO,
    MODULO_TECHNIC,
    PLACA,
    STUD,
    Bounds3D,
    Dimensions,
    GridPosition,
    Orientation,
)
from .history import CommandHistory
from .model import BlockModel, PlacedPart
from .parts import PartCatalog, PartDefinition
from .serialization import load_model, save_model

__all__ = [
    "BlockCADError",
    "CollisionError",
    "CommandError",
    "DslError",
    "DuplicateInstanceError",
    "DuplicatePartError",
    "InstanceNotFoundError",
    "InvalidColorError",
    "InvalidFormatError",
    "InvalidGeometryError",
    "InvalidPartError",
    "InvalidPlacementError",
    "PartNotFoundError",
    "TransactionError",
    "LDU_MM",
    "STUD",
    "PLACA",
    "LADRILLO",
    "MODULO_TECHNIC",
    "MEDIO_MODULO",
    "Bounds3D",
    "Dimensions",
    "GridPosition",
    "Orientation",
    "BlockModel",
    "PlacedPart",
    "PartCatalog",
    "PartDefinition",
    "load_model",
    "save_model",
    "parse_model",
    "parse_model_con_lineas",
    "Command",
    "AddPartCommand",
    "RemovePartCommand",
    "MovePartCommand",
    "TranslatePartCommand",
    "SetOrientationCommand",
    "RotateCommand",
    "RotateClockwiseCommand",
    "RecolorPartCommand",
    "MacroCommand",
    "CommandHistory",
    "BlockEditor",
]
